title: "Hu Lab"
description: "Our research focuses on understanding behaviors of large language models (LLMs), adapting them effectively to knowledge-intensive reasoning tasks, and aligning them safely with users from diverse backgrounds."

url: "https://madison-nlp.github.io"
baseurl: "/hu-lab"

markdown: kramdown
plugins: []

permalink: pretty